import { ResumeData } from '@/types/resume';

export const SAMPLE_RESUME: ResumeData = {
  id: 'sample-lpu-resume-1',
  title: 'Software Engineer Resume (LPU)',
  updatedAt: new Date().toISOString(),
  personalInfo: {
    fullName: 'Aarav Sharma',
    jobTitle: 'Full Stack Software Engineer',
    email: 'aarav.sharma@lpu.in',
    phone: '+91 98765 43210',
    location: 'Phagwara, Punjab, India',
    website: 'https://aaravsharma.dev',
    github: 'https://github.com/aaravsharma',
    linkedin: 'https://linkedin.com/in/aaravsharma-lpu',
    summary: 'Enthusiastic and results-driven Computer Science Engineering student at Lovely Professional University (LPU) with strong expertise in Next.js, React, Node.js, and Cloud Architectures. Proven track record in building scalable web applications and PWAs. Passionate about solving complex algorithms, open-source contribution, and software optimization.',
  },
  education: [
    {
      id: 'edu-1',
      institution: 'Lovely Professional University (LPU)',
      degree: 'Bachelor of Technology (B.Tech)',
      fieldOfStudy: 'Computer Science and Engineering',
      startDate: '2022',
      endDate: '2026 (Expected)',
      grade: 'CGPA: 8.85 / 10.0',
      description: 'Relevant Coursework: Data Structures & Algorithms, Database Management Systems, Web Technologies, Software Engineering, Computer Networks, and Cloud Computing.',
    },
    {
      id: 'edu-2',
      institution: 'Delhi Public School',
      degree: 'Higher Secondary Education (12th CBSE)',
      fieldOfStudy: 'Physics, Chemistry, Mathematics (PCM)',
      startDate: '2020',
      endDate: '2022',
      grade: '94.2%',
      description: 'Achieved top 5% rank in school; School Math Olympiad Winner.',
    },
  ],
  experience: [
    {
      id: 'exp-1',
      company: 'TechNovate Solutions',
      position: 'Software Development Intern',
      location: 'Bengaluru, India (Remote)',
      startDate: 'Jun 2025',
      endDate: 'Aug 2025',
      isCurrent: false,
      description: '• Developed responsive frontend interfaces using Next.js 15, Tailwind CSS, and TypeScript, improving page load speed by 35%.\n• Designed and integrated RESTful APIs with Node.js and PostgreSQL for a high-traffic analytics dashboard.\n• Implemented client-side caching and offline PWA service workers for seamless offline functionality.',
    },
    {
      id: 'exp-2',
      company: 'LPU Coding Community & Developer Club',
      position: 'Technical Lead & Mentor',
      location: 'Phagwara, Punjab',
      startDate: 'Aug 2024',
      endDate: 'Present',
      isCurrent: true,
      description: '• Organized 10+ university-level hackathons and technical workshops for over 500+ student developers.\n• Mentored junior students in Data Structures, React, and Git/GitHub version control workflows.',
    },
  ],
  skills: [
    { id: 'sk-1', name: 'TypeScript / JavaScript (ES6+)', category: 'Technical', level: 'Expert' },
    { id: 'sk-2', name: 'React.js & Next.js (App Router)', category: 'Technical', level: 'Expert' },
    { id: 'sk-3', name: 'Tailwind CSS & Responsive Web Design', category: 'Technical', level: 'Expert' },
    { id: 'sk-4', name: 'Node.js, Express & REST APIs', category: 'Technical', level: 'Advanced' },
    { id: 'sk-5', name: 'Git, GitHub Actions & Vercel Deployment', category: 'Tools', level: 'Advanced' },
    { id: 'sk-6', name: 'MongoDB & PostgreSQL', category: 'Technical', level: 'Intermediate' },
    { id: 'sk-7', name: 'PWA & Service Worker Caching', category: 'Technical', level: 'Advanced' },
    { id: 'sk-8', name: 'Problem Solving & Team Leadership', category: 'Soft Skills', level: 'Expert' },
  ],
  projects: [
    {
      id: 'proj-1',
      title: 'LPU Smart Campus Event Portal & PWA',
      technologies: 'Next.js, Tailwind CSS, LocalStorage, PWA Service Workers',
      link: 'https://github.com/aaravsharma/lpu-campus-pwa',
      startDate: 'Jan 2025',
      endDate: 'Mar 2025',
      description: '• Built a full-featured progressive web application for LPU campus events featuring real-time calendar syncing, offline access, and notification banners.\n• Handled local data caching with zero backend dependency, achieving 100/100 Lighthouse performance score.',
    },
    {
      id: 'proj-2',
      title: 'AI Resume & Portfolio Builder',
      technologies: 'React, TypeScript, HTML2PDF, Tailwind CSS',
      link: 'https://github.com/aaravsharma/resume-builder-pwa',
      startDate: 'Oct 2024',
      endDate: 'Dec 2024',
      description: '• Developed a client-side resume builder allowing real-time PDF generation and instant template styling.\n• Integrated client validation rules and local storage persistence for total user data privacy.',
    },
  ],
  templateId: 'modern',
  themeColor: 'indigo',
};
